---
sudo: false
language: perl
perl:
  - '5.20'
  - '5.10'
branches:
  only:
    - master
env:
  global:
    - AUTHOR_TESTING=0
    - AUTOMATED_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
script:
  perl Build.PL && ./Build && ./Build testcover
